name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  OCIR_REGION: nrt
  OCIR_NAMESPACE: ${{ secrets.OCIR_NAMESPACE }}
  PROJECT_NAME: sdb-sample

jobs:
  iac:
    name: Infrastructure as Code
    runs-on: ubuntu-latest
    needs: build-push
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: infra
    
    outputs:
      frontend_ci_id: ${{ steps.terraform.outputs.frontend_ci_id }}
      backend_ci_id: ${{ steps.terraform.outputs.backend_ci_id }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false
      
      - name: Configure OCI CLI
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          command: 'oci --version'
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format Check
        run: terraform fmt -check -diff -recursive
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_user_ocid: ${{ secrets.OCI_CLI_USER }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_CLI_TENANCY }}
          TF_VAR_fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          TF_VAR_compartment_id: ${{ secrets.OCI_COMPARTMENT_ID }}
          TF_VAR_ocir_repository: ${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}
          TF_VAR_image_tag: ${{ github.sha }}
          TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_user_ocid: ${{ secrets.OCI_CLI_USER }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_CLI_TENANCY }}
          TF_VAR_fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          TF_VAR_compartment_id: ${{ secrets.OCI_COMPARTMENT_ID }}
          TF_VAR_ocir_repository: ${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}
          TF_VAR_image_tag: ${{ github.sha }}
          TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
      
      - name: Get Terraform Outputs
        id: terraform
        run: |
          echo "frontend_ci_id=$(terraform output -raw frontend_container_instance_id)" >> $GITHUB_OUTPUT
          echo "backend_ci_id=$(terraform output -raw backend_container_instance_id)" >> $GITHUB_OUTPUT

  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        service: [frontend, backend]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ matrix.service }}-${{ github.sha }}
            ${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ matrix.service }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to OCI Container Instances
    runs-on: ubuntu-latest
    needs: [iac, build-push]
    if: github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        include:
          - service: frontend
            ci_id_var: frontend_ci_id
          - service: backend
            ci_id_var: backend_ci_id
    
    steps:
      - name: Configure OCI CLI
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          command: 'oci --version'
      
      - name: Set container configuration for ${{ matrix.service }}
        run: |
          if [ "${{ matrix.service }}" = "frontend" ]; then
            echo "IMAGE_URL=${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}:frontend-${{ github.sha }}" >> $GITHUB_ENV
            echo 'ENV_VARS={"NODE_ENV": "production", "PORT": "3000"}' >> $GITHUB_ENV
            echo "DISPLAY_NAME=nextjs" >> $GITHUB_ENV
          else
            echo "IMAGE_URL=${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}:backend-${{ github.sha }}" >> $GITHUB_ENV
            echo 'ENV_VARS={"NODE_ENV": "production", "PORT": "3001"}' >> $GITHUB_ENV
            echo "DISPLAY_NAME=nestjs" >> $GITHUB_ENV
          fi
      
      - name: Debug environment variables for ${{ matrix.service }}
        run: |
          echo "=== Environment Variables Debug ==="
          echo "SERVICE: ${{ matrix.service }}"
          echo "IMAGE_URL: ${IMAGE_URL}"
          echo "ENV_VARS: ${ENV_VARS}"
          echo "DISPLAY_NAME: ${DISPLAY_NAME}"
          echo "CI_ID: ${{ needs.iac.outputs[matrix.ci_id_var] }}"
          echo "OCIR_REGION: ${{ env.OCIR_REGION }}"
          echo "OCIR_NAMESPACE: ${{ env.OCIR_NAMESPACE }}"
          echo "PROJECT_NAME: ${{ env.PROJECT_NAME }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
      
      - name: Get Container Instance ID for ${{ matrix.service }} by name
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        run: |
            echo "=== Getting Container Instance ID for ${{ matrix.service }} ==="
            
            # Step 1: Test basic OCI CLI connectivity
            echo "Testing OCI CLI basic functionality..."
            oci --version || { echo "❌ OCI CLI not available"; exit 1; }
            
            # Step 2: Test compartment access
            echo "Testing compartment access..."
            oci iam compartment get --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} --query 'data.name' --raw-output || {
              echo "❌ Cannot access compartment ${{ secrets.OCI_COMPARTMENT_ID }}"
              exit 1
            }
            
            # Step 3: List all container instances (debug)
            echo "Listing all container instances in compartment..."
            oci container-instances container-instance list \
              --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
              --query 'data[].{"Name":"display-name","ID":"id","State":"lifecycle-state"}' \
              --output table || {
                echo "❌ Failed to list container instances"
                exit 1
              }
            
            # Step 4: Search for specific instance with detailed debugging
            INSTANCE_NAME="${{ env.PROJECT_NAME }}-${{ matrix.service }}"
            echo "Searching for instance: ${INSTANCE_NAME}"
            
            # First, show all instances with their exact names for comparison
            echo "All container instances with names:"
            oci container-instances container-instance list \
              --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
              --query 'data[].{"Name":"display-name","ID":"id"}' \
              --output table
            
            # Try exact match search
            echo "Trying exact match search for: '${INSTANCE_NAME}'"
            SEARCH_RESULT=$(oci container-instances container-instance list \
              --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
              --display-name "${INSTANCE_NAME}" \
              --query 'data' \
              --output json 2>&1 || echo "[]")
            
            echo "Search result JSON: ${SEARCH_RESULT}"
            
            # Extract ID if found (only ACTIVE instances)
            CONTAINER_INSTANCE_ID=$(echo "${SEARCH_RESULT}" | jq -r '.[] | select(."lifecycle-state" == "ACTIVE") | .id' 2>/dev/null || echo "")
            
            echo "Extracted Container Instance ID: '${CONTAINER_INSTANCE_ID}'"
            
            if [ -z "${CONTAINER_INSTANCE_ID}" ] || [ "${CONTAINER_INSTANCE_ID}" = "null" ]; then
              echo "❌ Failed to find container instance with exact name: ${INSTANCE_NAME}"
              
              # Try partial match as fallback
              echo "Trying partial match search..."
              oci container-instances container-instance list \
                --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
                --query "data[?contains(\"display-name\", '${{ matrix.service }}')].{\"Name\":\"display-name\",\"ID\":\"id\"}" \
                --output table
              
              exit 1
            fi
            
            echo "✅ Found Container Instance ID: ${CONTAINER_INSTANCE_ID}"
            echo "CONTAINER_INSTANCE_ID=${CONTAINER_INSTANCE_ID}" >> $GITHUB_ENV
      
      - name: Debug Container Instance ID for ${{ matrix.service }}
        run: |
          echo "=== Container Instance ID Debug ==="
          echo "CONTAINER_INSTANCE_ID value: '${CONTAINER_INSTANCE_ID}'"
          echo "CONTAINER_INSTANCE_ID length: ${#CONTAINER_INSTANCE_ID}"
          echo "CONTAINER_INSTANCE_ID first 20 chars: ${CONTAINER_INSTANCE_ID:0:20}"
          echo "CONTAINER_INSTANCE_ID last 20 chars: ${CONTAINER_INSTANCE_ID: -20}"
          
          # Check if ID looks like a valid OCID
          if [[ "${CONTAINER_INSTANCE_ID}" =~ ^ocid1\. ]]; then
            echo "✅ ID starts with ocid1. (looks valid)"
          else
            echo "❌ ID does not start with ocid1. (invalid format)"
          fi
      
      - name: Validate JSON syntax for ${{ matrix.service }}
        run: |
          echo "=== JSON Syntax Validation ==="
          echo "ENV_VARS JSON validation:"
          echo "${ENV_VARS}" | jq '.' || echo "❌ Invalid JSON in ENV_VARS"
          
          echo "Building complete container JSON:"
          CONTAINER_JSON="[{\"displayName\": \"${DISPLAY_NAME}\", \"imageUrl\": \"${IMAGE_URL}\", \"environmentVariables\": ${ENV_VARS}}]"
          echo "Container JSON: ${CONTAINER_JSON}"
          
          echo "Container JSON validation:"
          echo "${CONTAINER_JSON}" | jq '.' || echo "❌ Invalid container JSON syntax"
          
          if echo "${CONTAINER_JSON}" | jq '.' > /dev/null 2>&1; then
            echo "✅ JSON syntax is valid"
          else
            echo "❌ JSON syntax is invalid - this will cause OCI CLI to fail"
            exit 1
          fi
      
      - name: Show OCI CLI command for ${{ matrix.service }} (dry run)
        run: |
          echo "=== OCI CLI Command Preview ==="
          CONTAINER_JSON="[{\"displayName\": \"${DISPLAY_NAME}\", \"imageUrl\": \"${IMAGE_URL}\", \"environmentVariables\": ${ENV_VARS}}]"
          echo "Complete command that will be executed:"
          echo ""
          echo "oci container-instances container-instance update \\"
          echo "  --container-instance-id ${CONTAINER_INSTANCE_ID} \\"
          echo "  --containers '${CONTAINER_JSON}' \\"
          echo "  --force"
          echo ""
          echo "Command length: $(echo "oci container-instances container-instance update --container-instance-id ${CONTAINER_INSTANCE_ID} --containers '${CONTAINER_JSON}' --force" | wc -c) characters"
      
      - name: Test Container Instance Access for ${{ matrix.service }} (direct OCI CLI)
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        run: |
          echo "=== Testing Container Instance Access (Direct OCI CLI) ==="
          echo "Using Container Instance ID: ${CONTAINER_INSTANCE_ID}"
          
          # Step 1: Basic OCI CLI test
          echo "Step 1: Testing OCI CLI basic functionality..."
          oci --version || {
            echo "❌ OCI CLI not available or not configured"
            exit 1
          }
          
          # Step 2: Basic permissions test
          echo "Step 2: Testing basic container instances list permission..."
          oci container-instances container-instance list \
            --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
            --query 'data[0:2].{"ID":"id","Name":"display-name","State":"lifecycle-state"}' \
            --output table || {
              echo "❌ Basic list permission failed"
              exit 1
            }
          
          # Step 3: Full list to see all instances
          echo "Step 3: Listing all container instances..."
          oci container-instances container-instance list \
            --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
            --output table
          
          # Step 4: Test specific instance access
          echo "Step 4: Testing specific instance access..."
          echo "Container Instance ID: ${CONTAINER_INSTANCE_ID}"
          
          oci container-instances container-instance get \
            --container-instance-id "${CONTAINER_INSTANCE_ID}" \
            --query 'data.{"ID":"id","Name":"display-name","State":"lifecycle-state"}' \
            --output json || {
              EXIT_CODE=$?
              echo "❌ Get command failed with exit code: ${EXIT_CODE}"
              
              echo "Trying to find instance in list..."
              oci container-instances container-instance list \
                --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
                --query "data[?id=='${CONTAINER_INSTANCE_ID}']" \
                --output json
              
              exit ${EXIT_CODE}
            }
          
          echo "✅ Container instance access successful"
      
      - name: Update ${{ matrix.service }} Container Instance (with detailed debug)
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        run: |
          echo "=== Starting OCI CLI Update Command ==="
          set -x  # Enable command tracing
          
          # Prepare container JSON
          CONTAINER_JSON="[{\"displayName\": \"${DISPLAY_NAME}\", \"imageUrl\": \"${IMAGE_URL}\", \"environmentVariables\": ${ENV_VARS}}]"
          
          echo "Executing OCI CLI command..."
          oci container-instances container-instance update \
            --container-instance-id ${CONTAINER_INSTANCE_ID} \
            --containers "${CONTAINER_JSON}" \
            --force \
            --debug 2>&1 || {
              EXIT_CODE=$?
              echo "❌ OCI CLI failed with exit code: ${EXIT_CODE}"
              echo "=== Command that failed ==="
              echo "oci container-instances container-instance update --container-instance-id ${CONTAINER_INSTANCE_ID} --containers '${CONTAINER_JSON}' --force --debug"
              exit ${EXIT_CODE}
            }
          
          echo "✅ OCI CLI command completed successfully"
      
      - name: Wait for ${{ matrix.service }} Container Instance to be updated
        run: |
          echo "Waiting for container instance update to complete..."
          sleep 30
          
          # Check container instance status
          oci container-instances container-instance get \
            --container-instance-id ${CONTAINER_INSTANCE_ID} \
            --query 'data."lifecycle-state"' \
            --raw-output

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [iac, deploy]
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false
      
      - name: Configure OCI CLI
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          command: 'oci --version'
      
      - name: Get Load Balancer IP
        id: lb_ip
        working-directory: infra
        run: |
          terraform init
          echo "lb_ip=$(terraform output -raw load_balancer_public_ip)" >> $GITHUB_OUTPUT
        env:
          TF_VAR_user_ocid: ${{ secrets.OCI_CLI_USER }}
          TF_VAR_tenancy_ocid: ${{ secrets.OCI_CLI_TENANCY }}
          TF_VAR_fingerprint: ${{ secrets.OCI_CLI_FINGERPRINT }}
          TF_VAR_private_key: ${{ secrets.OCI_CLI_PRIVATE_KEY }}
          TF_VAR_compartment_id: ${{ secrets.OCI_COMPARTMENT_ID }}
          TF_VAR_ocir_repository: ${{ env.OCIR_REGION }}.ocir.io/${{ env.OCIR_NAMESPACE }}/${{ env.PROJECT_NAME }}
          TF_VAR_image_tag: ${{ github.sha }}
          TF_VAR_database_password: ${{ secrets.DATABASE_PASSWORD }}
      
      - name: Health Check - Frontend
        run: |
          echo "Checking frontend health at http://${{ steps.lb_ip.outputs.lb_ip }}"
          for i in {1..10}; do
            if curl -f -s http://${{ steps.lb_ip.outputs.lb_ip }}; then
              echo "Frontend is healthy!"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 30 seconds..."
            sleep 30
          done
          echo "Frontend health check failed"
          exit 1
      
      - name: Health Check - Backend API
        run: |
          echo "Checking backend health at http://${{ steps.lb_ip.outputs.lb_ip }}/api/health"
          for i in {1..10}; do
            if curl -f -s http://${{ steps.lb_ip.outputs.lb_ip }}/api/health; then
              echo "Backend API is healthy!"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 30 seconds..."
            sleep 30
          done
          echo "Backend API health check failed"
          exit 1